server:
  port: 8888
  contextPath: /
  session:
    timeout: 60

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
